using Microsoft.Extensions.VectorData;

namespace CompoundDocs.McpServer.Models;

/// <summary>
/// Represents a chunk of a large document (>500 lines) for semantic search.
/// Parent document reference maintained for context retrieval.
/// </summary>
/// <remarks>
/// Documents exceeding 500 lines are split into semantic chunks based on
/// markdown headers. Each chunk maintains a reference to its parent document
/// and inherits the parent's promotion level.
/// </remarks>
public sealed class DocumentChunk
{
    /// <summary>
    /// Unique identifier for the chunk (GUID string).
    /// </summary>
    [VectorStoreKey]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    #region Parent Reference

    /// <summary>
    /// Reference to the parent document's ID.
    /// Used for retrieving full document context.
    /// </summary>
    [VectorStoreData(IsIndexed = true)]
    public string DocumentId { get; set; } = string.Empty;

    #endregion

    #region Tenant Isolation (Inherited from Parent)

    /// <summary>
    /// Composite tenant key for multi-tenant isolation.
    /// Inherited from parent document.
    /// Format: project_name:branch_name:path_hash
    /// </summary>
    [VectorStoreData(IsIndexed = true)]
    public string TenantKey { get; set; } = string.Empty;

    #endregion

    #region Chunk Metadata

    /// <summary>
    /// Markdown header path representing the chunk's location in the document structure.
    /// Example: "## Configuration > ### Database Settings"
    /// </summary>
    [VectorStoreData]
    public string HeaderPath { get; set; } = string.Empty;

    /// <summary>
    /// Starting line number of this chunk in the source document (1-indexed).
    /// </summary>
    [VectorStoreData]
    public int StartLine { get; set; }

    /// <summary>
    /// Ending line number of this chunk in the source document (1-indexed, inclusive).
    /// </summary>
    [VectorStoreData]
    public int EndLine { get; set; }

    /// <summary>
    /// Content of this chunk for retrieval.
    /// </summary>
    [VectorStoreData]
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Promotion level inherited from parent document.
    /// Updated atomically when parent promotion changes.
    /// </summary>
    [VectorStoreData(IsIndexed = true)]
    public string PromotionLevel { get; set; } = PromotionLevels.Standard;

    #endregion

    #region Vector Embedding

    /// <summary>
    /// Vector embedding generated by mxbai-embed-large (1024 dimensions).
    /// Uses cosine distance with HNSW index for efficient similarity search.
    /// </summary>
    [VectorStoreVector(Dimensions: 1024)]
    public ReadOnlyMemory<float>? Vector { get; set; }

    #endregion

    /// <summary>
    /// Creates a new chunk from a parent document.
    /// </summary>
    /// <param name="parent">The parent document.</param>
    /// <param name="headerPath">The markdown header path.</param>
    /// <param name="content">The chunk content.</param>
    /// <param name="startLine">Starting line number.</param>
    /// <param name="endLine">Ending line number.</param>
    /// <returns>A new DocumentChunk instance.</returns>
    public static DocumentChunk CreateFromParent(
        CompoundDocument parent,
        string headerPath,
        string content,
        int startLine,
        int endLine)
    {
        return new DocumentChunk
        {
            DocumentId = parent.Id,
            TenantKey = parent.TenantKey,
            HeaderPath = headerPath,
            Content = content,
            StartLine = startLine,
            EndLine = endLine,
            PromotionLevel = parent.PromotionLevel
        };
    }

    /// <summary>
    /// Gets the line count of this chunk.
    /// </summary>
    public int LineCount => EndLine - StartLine + 1;
}
