# yaml-language-server: $schema=./skill-schema.json
---
name: /cdocs:recall
description: Contextual recall with multi-turn conversation support for documentation exploration
version: "1.0.0"

triggers:
  - recall
  - remember
  - follow up
  - continue
  - what about
  - tell me more

parameters:
  - name: query
    type: string
    description: The question or follow-up query
    required: true
    validation:
      min_length: 2

  - name: context_mode
    type: string
    description: Context handling mode (auto, new, continue)
    required: false
    default: auto
    validation:
      enum:
        - auto
        - new
        - continue

  - name: limit
    type: integer
    description: Maximum number of source documents per turn
    required: false
    default: 5
    validation:
      min: 1
      max: 20

  - name: doc_types
    type: string
    description: Comma-separated list of document types to filter by
    required: false

  - name: promotion_level
    type: string
    description: Minimum promotion level filter (standard, important, critical)
    required: false
    validation:
      enum:
        - standard
        - important
        - critical

  - name: include_history
    type: boolean
    description: Whether to include conversation history in context
    required: false
    default: true

tool_calls:
  - tool: rag_query
    arguments:
      query: "{{query}}"
      maxResults: "{{limit}}"
      includeContext: "{{include_history}}"
    result_variable: recall_result

output:
  format: markdown
  template: |
    # Recall Results

    **Query**: {{query}}
    {{#if recall_result.context.is_follow_up}}
    **Context**: Follow-up question (Turn {{recall_result.context.turn_number}})
    {{else}}
    **Context**: New conversation
    {{/if}}

    ## Answer

    {{recall_result.answer}}

    ## Sources

    {{#if recall_result.sources}}
    {{#each recall_result.sources}}
    - [{{title}}]({{file_path}}) ({{doc_type}}, relevance: {{relevance_score}})
    {{/each}}
    {{/if}}

    {{#if recall_result.suggested_follow_ups}}
    ## Suggested Follow-ups

    {{#each recall_result.suggested_follow_ups}}
    - {{this}}
    {{/each}}
    {{/if}}

    ---
    **Confidence**: {{recall_result.confidence_score}}
  include_tool_results: true

metadata:
  author: compound-docs
  category: query
  tags:
    - recall
    - context
    - conversation
    - follow-up
