# yaml-language-server: $schema=./skill-schema.json
---
name: /cdocs:search
description: Perform semantic vector similarity search across project documentation
version: "1.0.0"

triggers:
  - search
  - find documents
  - search docs
  - semantic search
  - find related
  - look for

parameters:
  - name: query
    type: string
    description: The search query text for semantic matching
    required: true
    validation:
      min_length: 2

  - name: limit
    type: integer
    description: Maximum number of results to return (1-100)
    required: false
    default: 10
    validation:
      min: 1
      max: 100

  - name: doc_types
    type: string
    description: Comma-separated list of document types to filter by (spec, adr, research, doc, guide, api, changelog)
    required: false

  - name: promotion_level
    type: string
    description: Minimum promotion level filter (standard, important, critical)
    required: false
    validation:
      enum:
        - standard
        - important
        - critical

  - name: min_relevance
    type: number
    description: Minimum relevance score threshold (0.0 to 1.0)
    required: false
    default: 0.0
    validation:
      min: 0.0
      max: 1.0

tool_calls:
  - tool: semantic_search
    arguments:
      query: "{{query}}"
      limit: "{{limit}}"
      docTypes: "{{doc_types}}"
      promotionLevel: "{{promotion_level}}"
    result_variable: search_result

output:
  format: markdown
  template: |
    # Search Results

    **Query**: {{query}}
    **Results Found**: {{search_result.total_results}}

    {{#if search_result.documents}}
    ## Documents

    {{#each search_result.documents}}
    ### {{title}}

    - **Path**: [{{file_path}}]({{file_path}})
    - **Type**: {{doc_type}}
    - **Promotion Level**: {{promotion_level}}
    - **Relevance**: {{relevance_score}}

    > {{content_snippet}}

    {{/each}}
    {{else}}
    _No documents matched your search query_
    {{/if}}
  include_tool_results: true

metadata:
  author: compound-docs
  category: query
  tags:
    - search
    - semantic
    - vector
    - discovery
