# yaml-language-server: $schema=./skill-schema.json
---
name: /cdocs:capture-style
description: Captures a style document describing coding standards, naming conventions, or formatting guidelines
version: "1.0.0"

triggers:
  - capture style
  - document style
  - capture convention
  - document convention
  - capture standard
  - document coding standard
  - capture formatting

parameters:
  - name: title
    type: string
    description: Title of the style guide
    required: true
    validation:
      min_length: 5
      max_length: 200

  - name: scope
    type: string
    description: What this style guide covers
    required: true
    validation:
      enum:
        - naming
        - formatting
        - architecture
        - testing
        - documentation
        - general

  - name: language
    type: string
    description: Programming language this applies to (if specific)
    required: false

  - name: description
    type: string
    description: Overview of the style guidelines
    required: true
    validation:
      min_length: 20

  - name: rules
    type: array
    description: Specific rules or guidelines
    required: true

  - name: examples_good
    type: array
    description: Examples of good practices
    required: false

  - name: examples_bad
    type: array
    description: Examples of practices to avoid
    required: false

  - name: rationale
    type: string
    description: Why these guidelines exist
    required: false

  - name: exceptions
    type: array
    description: Known exceptions to the rules
    required: false

  - name: enforcement
    type: string
    description: How the style is enforced (linter, review, etc.)
    required: false

  - name: related_styles
    type: array
    description: Related style documents
    required: false

  - name: tags
    type: array
    description: Tags for categorization
    required: false

tool_calls:
  - tool: index_document
    arguments:
      file_path: "{{generated_file_path}}"
    result_variable: index_result

output:
  format: markdown
  template: |
    ---
    doc_type: style
    title: "{{title}}"
    created: "{{timestamp}}"
    scope: {{scope}}
    {{#if language}}
    language: {{language}}
    {{/if}}
    {{#if tags}}
    tags:
    {{#each tags}}
      - {{this}}
    {{/each}}
    {{/if}}
    {{#if related_styles}}
    related:
    {{#each related_styles}}
      - {{this}}
    {{/each}}
    {{/if}}
    ---

    # {{title}}

    ## Overview

    {{description}}

    {{#if rationale}}
    ## Rationale

    {{rationale}}
    {{/if}}

    ## Rules

    {{#each rules}}
    - {{this}}
    {{/each}}

    {{#if examples_good}}
    ## Good Examples

    {{#each examples_good}}
    ### Example {{@index}}

    {{this}}

    {{/each}}
    {{/if}}

    {{#if examples_bad}}
    ## Anti-Patterns

    {{#each examples_bad}}
    ### What to Avoid {{@index}}

    {{this}}

    {{/each}}
    {{/if}}

    {{#if exceptions}}
    ## Exceptions

    {{#each exceptions}}
    - {{this}}
    {{/each}}
    {{/if}}

    {{#if enforcement}}
    ## Enforcement

    {{enforcement}}
    {{/if}}

    ## References

    _External references and resources_

metadata:
  author: compound-docs
  category: capture
  tags:
    - style
    - convention
    - standard
    - guidelines
