# yaml-language-server: $schema=./skill-schema.json
---
name: /cdocs:related
description: Find related documents using the document link graph and semantic similarity
version: "1.0.0"

triggers:
  - related
  - find related
  - related documents
  - linked documents
  - connections
  - what relates to

parameters:
  - name: file_path
    type: string
    description: File path of the document to find relations for (either file_path or query required)
    required: false

  - name: query
    type: string
    description: Search query to find a starting document (either file_path or query required)
    required: false

  - name: depth
    type: integer
    description: Depth of link traversal (1-3)
    required: false
    default: 1
    validation:
      min: 1
      max: 3

  - name: include_semantic
    type: boolean
    description: Include semantically similar documents in addition to linked documents
    required: false
    default: true

  - name: limit
    type: integer
    description: Maximum number of related documents to return
    required: false
    default: 10
    validation:
      min: 1
      max: 50

  - name: doc_types
    type: string
    description: Comma-separated list of document types to filter results
    required: false

  - name: link_types
    type: string
    description: Types of links to follow (all, outgoing, incoming, bidirectional)
    required: false
    default: all
    validation:
      enum:
        - all
        - outgoing
        - incoming
        - bidirectional

tool_calls:
  - tool: semantic_search
    arguments:
      query: "{{query}}"
      limit: "{{limit}}"
    condition: "query"
    result_variable: search_result

output:
  format: markdown
  template: |
    # Related Documents

    ## Source Document

    {{#if source_document}}
    - **Title**: {{source_document.title}}
    - **Path**: [{{source_document.file_path}}]({{source_document.file_path}})
    - **Type**: {{source_document.doc_type}}
    {{else}}
    _Source document not found_
    {{/if}}

    ## Related Documents

    {{#if related_documents}}
    {{#each related_documents}}
    ### {{title}}

    - **Path**: [{{file_path}}]({{file_path}})
    - **Type**: {{doc_type}}
    - **Relationship**: {{relationship.type}} (distance: {{relationship.distance}})
    - **Relevance**: {{relevance_score}}
    {{#if relationship.via_document}}
    - **Via**: {{relationship.via_document}}
    {{/if}}

    {{/each}}
    {{else}}
    _No related documents found_
    {{/if}}

    ## Link Summary

    - **Total Related**: {{link_summary.total_related}}
    - **Direct Links**: {{link_summary.direct_links}}
    - **Incoming Links**: {{link_summary.incoming_links}}
    - **Transitive Links**: {{link_summary.transitive_links}}
    {{#if include_semantic}}
    - **Semantic Matches**: {{link_summary.semantic_matches}}
    {{/if}}
  include_tool_results: true

metadata:
  author: compound-docs
  category: query
  tags:
    - related
    - links
    - graph
    - connections
