# yaml-language-server: $schema=./skill-schema.json
---
name: /cdocs:reindex
description: Forces reindexing of documents to update embeddings and metadata
version: "1.0.0"

triggers:
  - reindex
  - reindex document
  - reindex documents
  - refresh index
  - update index
  - rebuild index
  - resync

parameters:
  - name: file_paths
    type: string
    description: Comma-separated list of file paths to reindex. If empty, reindexes all documents
    required: false

  - name: doc_types
    type: string
    description: Comma-separated list of document types to reindex (e.g., spec,adr,problem)
    required: false

  - name: force
    type: boolean
    description: Force reindex even if documents appear unchanged
    required: false
    default: false

  - name: dry_run
    type: boolean
    description: If true, only preview what would be reindexed without actually reindexing
    required: false
    default: false

tool_calls:
  - tool: index_document
    arguments:
      filePath: "{{file_paths}}"
    condition: "{{file_paths}}"
    result_variable: index_result

output:
  format: markdown
  template: |
    # Document Reindex {{#if dry_run}}(Dry Run){{/if}}

    {{#if success}}
    {{#if dry_run}}
    ## Preview: Documents That Would Be Reindexed

    **Note**: This is a dry run. No documents were actually reindexed.
    {{else}}
    ## Reindex Complete
    {{/if}}

    ### Summary
    - **Documents Processed**: {{documents_processed}}
    - **Successfully Reindexed**: {{reindexed_count}}
    - **Chunks Created**: {{total_chunks}}
    - **Errors**: {{error_count}}

    {{#if reindexed_documents}}
    ### Reindexed Documents
    {{#each reindexed_documents}}
    - [{{title}}]({{file_path}})
      - Type: {{doc_type}}
      - Chunks: {{chunk_count}}
    {{/each}}
    {{/if}}

    {{#if errors}}
    ### Errors
    {{#each errors}}
    - **{{file_path}}**: {{error}}
    {{/each}}
    {{/if}}

    {{#if skipped_documents}}
    ### Skipped (Unchanged)
    {{#each skipped_documents}}
    - {{file_path}} - {{reason}}
    {{/each}}
    {{/if}}

    {{#if dry_run}}
    ---
    To actually reindex these documents, run:
    ```
    /cdocs:reindex {{#if file_paths}}file_paths="{{file_paths}}"{{/if}} dry_run=false
    ```
    {{/if}}
    {{else}}
    **Failed to reindex documents.**

    Error: {{error_message}}

    Please verify:
    - A project is currently active
    - The specified files exist
    {{/if}}

metadata:
  author: compound-docs
  category: utility
  tags:
    - reindex
    - refresh
    - maintenance
    - embeddings
