# yaml-language-server: $schema=./skill-schema.json
---
name: /cdocs:capture-tool
description: Captures a tool document describing a development tool, utility, script, or automation
version: "1.0.0"

triggers:
  - capture tool
  - document tool
  - log tool
  - document utility
  - capture script
  - document automation

parameters:
  - name: title
    type: string
    description: Name of the tool
    required: true
    validation:
      min_length: 2
      max_length: 100

  - name: description
    type: string
    description: What the tool does
    required: true
    validation:
      min_length: 20

  - name: tool_type
    type: string
    description: Type of tool
    required: false
    default: utility
    validation:
      enum:
        - cli
        - script
        - utility
        - automation
        - integration
        - library

  - name: installation
    type: string
    description: How to install or set up the tool
    required: false

  - name: usage
    type: string
    description: Basic usage instructions
    required: true
    validation:
      min_length: 10

  - name: examples
    type: array
    description: Usage examples
    required: false

  - name: options
    type: array
    description: Available options or flags
    required: false

  - name: dependencies
    type: array
    description: Required dependencies
    required: false

  - name: configuration
    type: string
    description: Configuration details
    required: false

  - name: limitations
    type: array
    description: Known limitations or caveats
    required: false

  - name: related_tools
    type: array
    description: Related tools
    required: false

  - name: tags
    type: array
    description: Tags for categorization
    required: false

tool_calls:
  - tool: index_document
    arguments:
      file_path: "{{generated_file_path}}"
    result_variable: index_result

output:
  format: markdown
  template: |
    ---
    doc_type: tool
    title: "{{title}}"
    created: "{{timestamp}}"
    tool_type: {{tool_type}}
    {{#if tags}}
    tags:
    {{#each tags}}
      - {{this}}
    {{/each}}
    {{/if}}
    {{#if related_tools}}
    related:
    {{#each related_tools}}
      - {{this}}
    {{/each}}
    {{/if}}
    ---

    # {{title}}

    ## Description

    {{description}}

    {{#if installation}}
    ## Installation

    {{installation}}
    {{/if}}

    ## Usage

    {{usage}}

    {{#if examples}}
    ## Examples

    {{#each examples}}
    ### Example {{@index}}

    {{this}}

    {{/each}}
    {{/if}}

    {{#if options}}
    ## Options

    {{#each options}}
    - {{this}}
    {{/each}}
    {{/if}}

    {{#if dependencies}}
    ## Dependencies

    {{#each dependencies}}
    - {{this}}
    {{/each}}
    {{/if}}

    {{#if configuration}}
    ## Configuration

    {{configuration}}
    {{/if}}

    {{#if limitations}}
    ## Limitations

    {{#each limitations}}
    - {{this}}
    {{/each}}
    {{/if}}

    ## Troubleshooting

    _Common issues and solutions_

metadata:
  author: compound-docs
  category: capture
  tags:
    - tool
    - utility
    - documentation
    - automation
