# yaml-language-server: $schema=./skill-schema.json
---
name: /cdocs:deactivate
description: Deactivates the current project, clearing all session state
version: "1.0.0"

triggers:
  - deactivate project
  - deactivate
  - close project
  - clear project
  - reset session

parameters:
  - name: confirm
    type: boolean
    description: Confirm deactivation (required to prevent accidental deactivation)
    required: false
    default: true

tool_calls: []

output:
  format: markdown
  template: |
    # Project Deactivated

    {{#if was_active}}
    Successfully deactivated project:

    - **Previous Project**: {{previous_project_name}}
    - **Previous Branch**: {{previous_branch_name}}

    Session state has been cleared. You can activate a new project with:
    ```
    /cdocs:activate <project_path>
    ```
    {{else}}
    **No project was active.**

    There is no active project to deactivate.
    {{/if}}

metadata:
  author: compound-docs
  category: meta
  tags:
    - project
    - deactivation
    - cleanup
