# yaml-language-server: $schema=./skill-schema.json
---
name: /cdocs:demote
description: Demotes a document's visibility in RAG results by decreasing its promotion level
version: "1.0.0"

triggers:
  - demote document
  - demote
  - unboost document
  - unpin document
  - decrease priority
  - make standard
  - reset priority

parameters:
  - name: file_path
    type: string
    description: The relative path to the document from the project root
    required: true
    validation:
      min_length: 1

  - name: level
    type: string
    description: The target promotion level to demote to
    required: false
    default: standard
    validation:
      enum:
        - standard
        - promoted
        - important

tool_calls:
  - tool: update_promotion_level
    arguments:
      filePath: "{{file_path}}"
      promotionLevel: "{{level}}"
    result_variable: demotion_result

output:
  format: markdown
  template: |
    # Document Demoted

    {{#if success}}
    Successfully updated document promotion level:

    - **Document**: [{{demotion_result.title}}]({{demotion_result.file_path}})
    - **Previous Level**: {{demotion_result.previous_level}}
    - **New Level**: {{demotion_result.new_level}}
    - **Boost Factor**: {{demotion_result.boost_factor}}x

    The document will now appear with {{demotion_result.boost_factor}}x relevance weighting in RAG search results.

    ### Promotion Levels
    | Level | Boost | Description |
    |-------|-------|-------------|
    | standard | 1.0x | Normal relevance scoring |
    | promoted | 1.5x | Boosted in search results |
    | pinned | 2.0x | Maximum visibility |
    {{else}}
    **Failed to demote document.**

    Error: {{error_message}}

    Please verify:
    - A project is currently active
    - The document exists and is indexed
    - The file path is correct
    {{/if}}
  include_tool_results: true

metadata:
  author: compound-docs
  category: utility
  tags:
    - promotion
    - visibility
    - priority
    - demote
